import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

async function testPDF() {
  console.log('Testing PDF generation...');
  
  try {
    const pdfDoc = await PDFDocument.create();
    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    const page = pdfDoc.addPage([600, 800]);
    const { width, height } = page.getSize();
    const margin = 50;
    let y = height - margin;

    const drawText = (text: string, size: number = 12, isBold: boolean = false, indent: number = 0) => {
      const f = isBold ? boldFont : font;
      page.drawText(text, {
        x: margin + indent,
        y,
        size,
        font: f,
        color: rgb(0, 0, 0),
      });
      y -= size + 8;
    };

    drawText('Test PDF Document', 20, true);
    drawText('This is a test PDF generated by pdf-lib', 12);

    const pdfBytes = await pdfDoc.save();
    console.log('PDF generated, size:', pdfBytes.length, 'bytes');

    const outputPath = path.join(__dirname, '../data/test.pdf');
    fs.writeFileSync(outputPath, Buffer.from(pdfBytes));
    console.log('PDF saved to:', outputPath);
  } catch (error) {
    console.error('Error:', error);
  }
}

testPDF();
